# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170712_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='postformonth',
            name='title',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postall',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postarabic',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postbengali',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postchinese',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postenglish',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postfrench',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postgerman',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='posthindi',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postjapanese',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postjavanese',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postkorean',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postlahnda',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postmalay',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postportuguese',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postrussian',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='postspanish',
            name='text',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='posttelugu',
            name='text',
            field=models.TextField(max_length=110),
        ),
    ]
