# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postforhourcomment_postformonthcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postformonthcomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostForMonth',
        ),
        migrations.DeleteModel(
            name='PostForMonthComment',
        ),
    ]
